-- 50 photo-scavenger tasks, split easy/medium/hard.
-- Scores: easy 10, medium 20, hard 35.
insert into public.tasks (title, description, difficulty, score) values
('Front door', 'Take a photo of your front door.', 'easy', 10),
('Your shoes', 'Take a photo of the shoes you are wearing.', 'easy', 10),
('A red object', 'Take a photo of anything red.', 'easy', 10),
('Street sign', 'Take a photo of a street sign near you.', 'easy', 10),
('A tree', 'Take a photo of a tree.', 'easy', 10),
('Your reflection', 'Take a photo of yourself in a mirror or window.', 'easy', 10),
('A book', 'Take a photo of a book cover.', 'easy', 10),
('Kitchen sink', 'Take a photo of a kitchen sink.', 'easy', 10),
('A clock', 'Take a photo of a clock showing the time.', 'easy', 10),
('A plant', 'Take a photo of a houseplant or garden plant.', 'easy', 10),
('A car', 'Take a photo of any parked car.', 'easy', 10),
('Sky above', 'Take a photo straight up at the sky.', 'easy', 10),
('A cup', 'Take a photo of a mug or cup.', 'easy', 10),
('Your pet', 'Take a photo of a pet (yours or a neighbor''s, with permission).', 'easy', 10),
('A light switch', 'Take a photo of a light switch.', 'easy', 10),
('A staircase', 'Take a photo of a staircase.', 'easy', 10),
('Bicycle', 'Take a photo of a bicycle.', 'easy', 10),
('A bridge', 'Take a photo of a bridge, big or small.', 'medium', 20),
('Local landmark', 'Take a photo of a well-known landmark in your city.', 'medium', 20),
('Something yellow', 'Take a photo of three yellow objects in one frame.', 'medium', 20),
('Graffiti or street art', 'Take a photo of graffiti or public street art.', 'medium', 20),
('A fountain', 'Take a photo of a fountain.', 'medium', 20),
('Public transport', 'Take a photo of a bus, train, or tram.', 'medium', 20),
('Storefront sign', 'Take a photo of a shop sign written in a font you like.', 'medium', 20),
('A shadow', 'Take a photo where a shadow is the main subject.', 'medium', 20),
('Reflection in water', 'Take a photo of something reflected in water.', 'medium', 20),
('A statue', 'Take a photo of a statue or monument.', 'medium', 20),
('Sunset or sunrise', 'Take a photo of a sunset or sunrise.', 'medium', 20),
('A crowd', 'Take a photo of a crowd of at least 5 people (no faces required).', 'medium', 20),
('Symmetry', 'Take a photo where the composition is symmetrical.', 'medium', 20),
('A rooftop view', 'Take a photo from an elevated viewpoint (balcony, hill, rooftop).', 'medium', 20),
('Local food', 'Take a photo of a local dish or snack.', 'medium', 20),
('A door number', 'Take a photo of a house or building number.', 'medium', 20),
('Public art installation', 'Take a photo of a public art installation or mural.', 'medium', 20),
('A market stall', 'Take a photo of a market or street vendor stall.', 'medium', 20),
('Something in motion', 'Take a photo capturing motion blur.', 'medium', 20),
('A staircase from above', 'Take a photo looking down a staircase.', 'medium', 20),
('Bird in the wild', 'Take a photo of a bird outdoors.', 'hard', 35),
('Historic building', 'Take a photo of a building over 50 years old.', 'hard', 35),
('City skyline', 'Take a photo of a full city skyline.', 'hard', 35),
('Rainbow', 'Take a photo of a rainbow.', 'hard', 35),
('Star or moon', 'Take a photo of the moon or a visible star at night.', 'hard', 35),
('A waterfall', 'Take a photo of a waterfall.', 'hard', 35),
('Wildlife up close', 'Take a photo of a wild animal (not a pet) up close.', 'hard', 35),
('Aerial-style shot', 'Take a photo from the highest point you can safely reach.', 'hard', 35),
('Storm or lightning', 'Take a photo of a storm, heavy rain, or lightning.', 'hard', 35),
('Two landmarks in one shot', 'Take a photo containing two different landmarks in frame.', 'hard', 35),
('A double rainbow effect', 'Take a photo showing light refraction (prism, rainbow, lens flare).', 'hard', 35),
('Panoramic view', 'Take a wide panoramic photo of a landscape.', 'hard', 35),
('Nighttime cityscape', 'Take a photo of a lit-up city at night.', 'hard', 35)
on conflict (title) do nothing;
